### ISSUE TITLE
New problems arise because of the absence of some other packages.

### ISSUE THREAD

**Issue by Sillouevan** [logpai/AutoLog#7]
Could you please update the package "treeEditDistance" for these missing classes and upload the package "analyze"?
Thanks for your great help, again.
![1](https://github.com/logpai/AutoLog/assets/152054620/683a7ab5-1a75-48ee-965b-99aea254cea4)
![2](https://github.com/logpai/AutoLog/assets/152054620/c6a0d19b-329d-4cf0-b5bb-e61c609b7d82)
![3](https://github.com/logpai/AutoLog/assets/152054620/2c9f33fe-790b-4807-b551-61fd9829a269)

**Comment by YichenLi00** [comment]
Will upload these code in the coming week

**Comment by YichenLi00** [comment]
> Besides the above, some other packages are also missing: ![image](https://private-user-images.githubusercontent.com/93540069/287693745-744562c3-0c4c-482e-a7a5-f433a8adab31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTI0NDUsIm5iZiI6MTcwMTY5MjE0NSwicGF0aCI6Ii85MzU0MDA2OS8yODc2OTM3NDUtNzQ0NTYyYzMtMGM0Yy00ODJlLWE3YTUtZjQzM2E4YWRhYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEyMTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYTU2NTAzZmQ1NGQ0ZTAyMjZkMjBkY2JkYTY0ODAzOTBkOTRlMDU5Y2IyNDY4NDkzZDkzMjRiN2EzNDU1Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9-3VGIeI1P6hODoFwEsNBP3sTtqkiNbFU5iO1k9utx4) ![image](https://private-user-images.githubusercontent.com/93540069/287693797-11cd1775-da48-4247-8d24-7300a64edd8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTI0NDUsIm5iZiI6MTcwMTY5MjE0NSwicGF0aCI6Ii85MzU0MDA2OS8yODc2OTM3OTctMTFjZDE3NzUtZGE0OC00MjQ3LThkMjQtNzMwMGE2NGVkZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEyMTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzNGE3NWNhYjIzN2ZhZmI1YzJjMmVmMjMwMDRjZjg0YWE0MjE3NTc0NTE2Mzc1NTg2NGY5NDVjNDg0NzY3NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pki9BtSkUj524fmSFX9PlfAqhiuZ2xzFmStKR46fdA4) ![image](https://private-user-images.githubusercontent.com/93540069/287693821-fc0ddd5c-5c00-42ce-8267-07b0db71e604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTI0NDUsIm5iZiI6MTcwMTY5MjE0NSwicGF0aCI6Ii85MzU0MDA2OS8yODc2OTM4MjEtZmMwZGRkNWMtNWMwMC00MmNlLTgyNjctMDdiMGRiNzFlNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEyMTU0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNDg2ZDAwYTI3YzE0YjM3MzNkOTEzMWJiYjIyMjg0OGZiNDBkMmVmOTYxZDM3ZWJmMjdhYzhkOTYxZDAwMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jv2synt0jeK-iVeQq6HtpXwddOQOl3wSi7lvMvI6JRk)

There packages are all about detailed contain solving  which can make LogEP preciser. I will fix this issue in the coming week. 
In fact, it would not hinder the main function of the whole project.

**Comment by YichenLi00** [comment]
> Besides the above, some other packages are also missing: ![image](https://private-user-images.githubusercontent.com/93540069/287693745-744562c3-0c4c-482e-a7a5-f433a8adab31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTM2ODAsIm5iZiI6MTcwMTkxMzM4MCwicGF0aCI6Ii85MzU0MDA2OS8yODc2OTM3NDUtNzQ0NTYyYzMtMGM0Yy00ODJlLWE3YTUtZjQzM2E4YWRhYjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAxNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhOWQxNWJhY2Y4MDlhOTIyZDdiMTAzZWNmMWFlMTk2MmM0ODgxYTdkMjhmZjliOGNiZjA5MmE4NDBhM2Y0NDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iFOSCkBknhB789vq0Gde12-lRD_FutyDTWQ_3pqZjTU) ![image](https://private-user-images.githubusercontent.com/93540069/287693797-11cd1775-da48-4247-8d24-7300a64edd8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTM2ODAsIm5iZiI6MTcwMTkxMzM4MCwicGF0aCI6Ii85MzU0MDA2OS8yODc2OTM3OTctMTFjZDE3NzUtZGE0OC00MjQ3LThkMjQtNzMwMGE2NGVkZDhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAxNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MzE0MWE1Y2VhYTIwMmRkODQ3OWI4OWU1MzYxNDE3NzQ3ZTVlMTUwM2Q4YzQwYmQ4N2RlZDlkODRlN2YxYTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xj7ye54JnD3_5ngeHbsnuD94RgOvFQTFC0mKFI3AsZA) ![image](https://private-user-images.githubusercontent.com/93540069/287693821-fc0ddd5c-5c00-42ce-8267-07b0db71e604.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MTM2ODAsIm5iZiI6MTcwMTkxMzM4MCwicGF0aCI6Ii85MzU0MDA2OS8yODc2OTM4MjEtZmMwZGRkNWMtNWMwMC00MmNlLTgyNjctMDdiMGRiNzFlNjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDAxNDMwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjN2I1ZDdmMGU2MWU0ZWFhOGY5NjhhZTk1ZjFiZjM0ZDkxYWE2MTVkYzYxMWE1Mzg2NjcxYzU2OGY1MDNhMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VhxFYkKfpLFlwQFqtSy2UqWYy0AsFKPqIa-GKpPdcIA)

You can get these packages from my coauthor's work https://github.com/CGCL-codes/PHunter

If you have further questions, please let me know.
