### ISSUE TITLE
Step4: LogEPGen.jar doesn't work

### ISSUE THREAD

**Issue by WMwzy** [logpai/AutoLog#8]
Hello! I have tried step4 on several operating systems(ubuntu, win) and using 2 versions of jdk(openjdk-8-jdk and 17) but gained the same results, which output the same information "usage: OptionsUsage" even if there exists the parameter '-j'
```
usage: OptionsUsage
 -h,--help          Print usage
 -j,--jarName       Jar file to contain the Log Statements
 -l,--LogMethods    LogMethods to analyze
 -m,--matcher       Matcher for Log API
 -o,--Output        Output file
```
sreenshots are below:
![KV0T3`YUVMXVPCQJN)A_VJR](https://github.com/logpai/AutoLog/assets/93540069/cd289240-7acd-421d-a250-6be2cb595131)
![FGC2}CSD Z_YH@9UG)JBO$O](https://github.com/logpai/AutoLog/assets/93540069/1f2e02e0-8b69-46e5-ba9b-bb0a10b1c6db)

**Comment by YichenLi00** [comment]
I will fix this issue in the coming week.
